# site settings
title: Personal Training by Alex Rico
subtitle: A personal trainer based in Eastbourne
email: training@alexri.co
description:  Certified personal trainer. Bespoke PT sessions (1 on 1, 1 on 2, small groups). Get in touch for more information.
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://alexricopt.github.io # the base hostname & protocol for your site
author:
street_address: 
city:
state: 
zip_code: 
country:
phone:
permalink: /:title/

repository: alexricopt.github.io/training

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# social settings
facebook_url: 
instagram_url: https://www.instagram.com/alexricopt/
youtube_url: 

# build settings
markdown: kramdown

sass:
  style: compressed

# sitemap
plugins:
  - jekyll-sitemap
  - jekyll-airtable
  - environment_variables_generator

airtable:
  enable_sync: true
  base_uid: 'appp7C1MblPCnMePn'
  airtable_api_key: ${{ secrets.GH_PAGES_TOKEN }}
  tables:
    - name: 'Use Cases' 
    - name: 'Whitepapers'    
    - name: 'Quotes'
      long_text_columns:
        - 'column name'